backend-build:
  stage: build
  script:
    - nix-build -A agora-backend
  tags:
    - shell-executor

backend-whitespace:
  stage: test
  script:
    - nix-build -A agora-backend-trailing-whitespace
  tags:
    - shell-executor

backend-haddock:
  stage: test
  script:
    - nix-build -A agora-backend-haddock
  tags:
    - shell-executor

frontend-build:
  stage: build
  script:
    - nix-build -A agora-frontend
  tags:
    - shell-executor

frontend-whitespace:
  stage: test
  script:
    - nix-build -A agora-frontend-trailing-whitespace
  tags:
    - shell-executor
