node_addr: "staging.agora.tezos.serokell.org:8732"
tzscan_url: "https://api6.tzscan.io/v3"

api:
  listen_addr: "*:8190"
  serve_docs: true

logging:
  backends:
  - type: stderr
  min-severity: Debug

db:
  # Syntax: https://www.postgresql.org/docs/9.5/libpq-connect.html#LIBPQ-CONNSTRING
  conn_string: "host=/run/postgresql dbname=agora"
  max_connections: 200
