node_addr: "3.9.20.98:8732"

api:
  listen_addr: "*:8190"
  serve_docs: true

logging:
  backends:
  - type: stderr
  min-severity: Debug

db:
  # Syntax: https://www.postgresql.org/docs/9.5/libpq-connect.html#LIBPQ-CONNSTRING
  conn_string: "host=/run/postgresql dbname=agora"
  max_connections: 200

empty_periods: 10 # since blocks in [0..9] periods
                  # don't contain any voting information
