node_addr: "babylon.testnet.tezos.serokell.team:8732"

api:
  listen_addr: "*:8190"
  serve_docs: true

logging:
  backends:
  - type: stderr
  min-severity: Debug

contract:
  address: "KT1LizLcyJErLfohpeN6NR9rKvrus7Hk7UC9"

db:
  # Syntax: https://www.postgresql.org/docs/9.5/libpq-connect.html#LIBPQ-CONNSTRING
  conn_string: "host=/run/postgresql dbname=agora"
  max_connections: 200

discourse:
  host: https://tezos.discourse.group
  category: Proposals
  api_username: tezosagora

