name:                agora
version:             0.1.0.0
license:             AGPL-3.0-or-later
author:              Serokell
maintainer:          Serokell <hi@serokell.io>
copyright:           2019 Tocqueville Group
git:                 git@gitlab.com:serokell/agora.git


extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

description:
  Backend of Agora web application.
  Agora is an explorer of Tezos voting system which helps
  users to follow current voting, be aware of suggested proposals,
  discuss new proposals, etc.

default-extensions:
- AllowAmbiguousTypes
- BangPatterns
- ConstraintKinds
- DataKinds
- DefaultSignatures
- DeriveDataTypeable
- DeriveGeneric
- EmptyCase
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GeneralizedNewtypeDeriving
- LambdaCase
- MonadFailDesugaring
- MultiParamTypeClasses
- MultiWayIf
- NamedFieldPuns
- OverloadedStrings
- OverloadedLabels
- PatternSynonyms
- RankNTypes
- RecordWildCards
- ScopedTypeVariables
- StandaloneDeriving
- TemplateHaskell
- TupleSections
- TypeFamilies
- TypeOperators
- UndecidableInstances
- ViewPatterns
- TypeApplications

dependencies:
- base-noprelude >= 4.9 && < 5
- loot-prelude
- universum
- microlens-platform

ghc-options:
# workaround for building with -Werror on macos+clang
- -optP-Wno-nonportable-include-path
- -Wall
- -fno-warn-orphans
- -Widentities
- -Wincomplete-record-updates
- -Werror

library:
  source-dirs: src
  build-tools:
  - autoexporter
  dependencies:
  - aeson
  - aeson-options
  - time
  - servant
  - servant-server
  - servant-util
  - warp

executables:
  agora:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - agora

tests:
  agora-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - agora
