name:                agora
version:             0.1.0.0
license:             AGPL-3.0-or-later
author:              Serokell
maintainer:          Serokell <hi@serokell.io>
copyright:           2019 Tocqueville Group
git:                 git@gitlab.com:serokell/agora.git


extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

description:
  Backend of Agora web application.
  Agora is an explorer of Tezos voting system which helps
  users to follow current voting, be aware of suggested proposals,
  discuss new proposals, etc.

default-extensions:
- AllowAmbiguousTypes
- BangPatterns
- ConstraintKinds
- DataKinds
- DefaultSignatures
- DeriveDataTypeable
- DeriveGeneric
- DerivingStrategies
- EmptyCase
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GeneralizedNewtypeDeriving
- LambdaCase
- MonadFailDesugaring
- MultiParamTypeClasses
- MultiWayIf
- NamedFieldPuns
- OverloadedStrings
- OverloadedLabels
- PatternSynonyms
- RankNTypes
- RecordWildCards
- ScopedTypeVariables
- StandaloneDeriving
- TemplateHaskell
- TupleSections
- TypeFamilies
- TypeOperators
- UndecidableInstances
- ViewPatterns
- TypeApplications

dependencies:
- base-noprelude >= 4.9 && < 5
- bytestring
- loot-prelude
- universum
- microlens-platform

ghc-options:
# workaround for building with -Werror on macos+clang
- -optP-Wno-nonportable-include-path
- -Wall
- -fno-warn-orphans
- -Widentities
- -Wincomplete-record-updates
- -Werror

library:
  source-dirs: src
  build-tools:
  - autoexporter
  dependencies:
  - aeson
  - aeson-options
  - base58-bytestring
  - beam-core
  - beam-postgres
  - caps
  - containers
  - file-embed
  - fmt
  - generic-arbitrary
  - http-client
  - loot-log
  - loot-config
  - mtl
  - optparse-applicative
  - parser-combinators
  - postgresql-simple
  - resource-pool
  - text
  - time
  - unliftio
  - vinyl
  - servant
  - servant-client
  - servant-client-core
  - servant-server
  - servant-swagger
  - servant-swagger-ui
  - servant-swagger-ui-core
  - servant-util
  - swagger2
  - unordered-containers
  - QuickCheck
  - unliftio-core
  - wai-cors
  - warp
  - yaml

executables:
  agora:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aeson
    - agora
    - optparse-applicative

  agora-swagger-gen:
    main:                Main.hs
    source-dirs:         tools/swagger-gen
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - agora
    - yaml

tests:
  agora-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    build-tools:
    - hspec-discover
    dependencies:
    - agora
    - aeson
    - beam-core
    - beam-postgres
    - caps
    - hspec
    - loot-log
    - postgresql-simple
    - unliftio
    - servant-swagger
    - QuickCheck
    - yaml
