resolver: lts-14.16

packages:
- .

extra-deps:
- aeson-options-0.1.0
- base58-bytestring-0.1.0

- git: https://github.com/serokell/zeromq-haskell.git
  commit: 714ac20981b2d346609fd896a1af4d31eb6d1162

- git: https://github.com/serokell/co-log-sys.git
  commit: a699c4eb00e413eb3cb2e9b34bfc7c1451b21279

- git: https://github.com/int-index/caps.git
  commit: ab4345eabd58fc6f05d3b46bea2c5acdba3ec6f8

- git: https://gitlab.com/obsidian.systems/tezos-bake-monitor-lib.git
  commit: 19a9ce57a0510bc3ad8a3f639d0a968a65024b86
  subdirs:
    - tezos-bake-monitor-lib

- git: https://github.com/serokell/staker-dao.git
  commit: 591a13e14ade43bbd4f04ce024c92aa5ddee3d0d
  subdirs:
    - stkr-token

- time-units-1.0.0

# Has slightly more sane interface than 7
- megaparsec-8.0.0

# required by servant-util
- pretty-terminal-0.1.0.0

# required by loot-log
- componentm-0.0.0.2
- teardown-0.5.0.1

- html-parse-0.2.0.2

# pva701: If you experience fail of a building due to error like "not found yaml file"
# you probably have stack with version 2.1+ and it seems not to manage with git packages
# which are based on hpack. You should downgrade your stack to 1.9. It should help.
- git: https://github.com/serokell/servant-util.git
  commit: 34a98ee92812096f624dfe52b4fdf338a021e8ba
  subdirs:
    - servant-util

# Lootbox (prelude, logging, configuration)
- git: https://github.com/serokell/lootbox.git
  commit: 4700376b8493f6ac164461715cb72a0259148ac2
  subdirs:
    - code/base
    - code/config
    - code/log
    - code/prelude

- git: https://gitlab.com/morley-framework/morley.git
  commit: ee40fe4e2b08c7e24a90c9112de0c7ad936cc47d # master
  subdirs:
    - .
    - prelude

# Required by morley
- show-type-0.1.1@sha256:24f681a3481b3f9630e619d816054804ba1bd6cc05b5978ddd2cece8499ff2fa
- hex-text-0.1.0.0
- first-class-families-0.6.0.0
- constraints-0.11@sha256:44f80a313d5d4fcfb3c18eb6625dd3db4bb845d5ca8d3b1f62125a4b7241e590

# Required by tezos-bake-monitor-lib
- functor-infix-0.0.5@sha256:cea21a321031f556d7a21b51e049493e7cb78baf64dd63f0d1a36de01c4c735b
- hashing-0.1.0.1@sha256:98861f16791946cdf28e3c7a6ee9ac8b72d546d6e33c569c7087ef18253294e7
- dependent-sum-0.5
- dependent-sum-template-0.1.0.0
- constraints-extras-0.3.0.2@sha256:bf6884be65958e9188ae3c9e5547abfd6d201df021bff8a4704c2c4fe1e1ae5b

# Work-around for haskell.nix patches. Delete when switching to LTS >= 15.
# See the singletons commit for details.
# This commit is singletons-2.5.1 with a patch that fixes the issue.
- git: https://github.com/serokell/singletons
  commit: 78bfaa74891bd0fc6754c802a6ec649854af92c1  # kirelagin/template-haskell-uniq/v.2.5.1

nix:
  shell-file: nix/stack-shell.nix
